# Generated by Django 3.0.3 on 2020-06-03 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('no_units', models.IntegerField()),
                ('theory_hours', models.IntegerField()),
                ('practice_hours', models.IntegerField()),
                ('credit', models.IntegerField(db_column='credits', verbose_name='credits')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.Group')),
                ('students', models.ManyToManyField(to='students.Student')),
            ],
        ),
    ]
